extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/tNncEMhCqZ
      name: Bixie Bash Discord server

    - icon: fontawesome/brands/mastodon
      link: https://furries.club/@anebix
      name: Anebix Mastodon at furries.club

    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/anebixworld
      name: Anebix Pinterest

    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@anebix
      name: Anebix YouTube

    - icon: fontawesome/brands/pixiv
      link: https://www.pixiv.net/en/users/108714886
      name: Anebix Pixiv

site_name: Anebix World
theme:
  name: material
